### get-cell-type-proportion.R ####################################################################
# PURPOSE: for collection of proportion result file generated by get-cell-type-proportion.R,
# merge these data together and output a summary table

### PREAMBLE ######################################################################################
# load in library:
require(ComplexHeatmap);
require(circlize);

# define the input and its help page:
require(docopt)
'Usage:
    get-cell-type-proportion.R [--dir <directory> --keyword <group> --cutoff <cells> --out <output>]

Options:
    --keyword keyword to grab the files with (differentiate which files are of interest)
    --dir directory that the proportion files resides in
    --cutoff minimum number of significant cells for the individual proportion file to be considered
    --out directory to output heatmap plot and actual table
]' -> doc

# collect user input: 
opts <- docopt(doc)
proportion.dir <- opts$dir;
keyword <- opts$keyword;
min.cell <- as.numeric(opts$cutoff);
output.path <- opts$out;
system.date <- Sys.Date();

### MERGE #########################################################################################
# first read in the tables that we are interested in reading:
result.file <- list.files(proportion.dir, pattern = keyword);

# initiate place holder:
result <- vector('list', length = length(result.file));
names(result) <- gsub('-proportions.txt', '', result.file);

# from the initiated place holder read in the data:
filter.criteria = {}
for (index in seq(1, length(result.file))) {
    result[[index]] <- read.table(
        file = paste0(proportion.dir, result.file[index]),
        sep = '\t',
        header = TRUE,
        stringsAsFactors = FALSE
        );

    # check for filtering cutoff:
    filter.criteria[index] <- sum(result[[index]]$cell.number) > min.cell;
    }

result.filter <- result[filter.criteria];

# next start merging:
merged.result <- result.filter[[1]][, c('group', 'percentage')];
colnames(merged.result) <- c('group', names(result.filter)[1]);
for (index in seq(1, length(result.filter) - 1)) {
    previous.name <- colnames(merged.result);
    merged.result <- merge(
        x = merged.result,
        y = result.filter[[index + 1]][, c('group', 'percentage')],
        all = TRUE,
        by = 'group'
        );
    colnames(merged.result) <- c(previous.name, names(result.filter)[index + 1]);
    }
merged.result[is.na(merged.result)] <- 0;
merged.result <- data.frame(merged.result, row.names = 1);

# sanity check:
if (min.cell > 0) {
    stopifnot(signif(colSums(merged.result), 1e14) == 100);
    }

for (index in seq(1, ncol(merged.result))) {
    merged.column <- sort(merged.result[, index], decreasing = TRUE);
    merged.column <- merged.column[merged.column != 0 ];
    stopifnot(result.filter[[index]]$percentage == merged.column)
    }
cat('merge completed!\n')

# make the heatmap:
col.fun <- colorRamp2(c(0, 100), c('white', '#de2d26'));
plot <- Heatmap(
    as.matrix(merged.result),
    name = 'prop',
    col = col.fun,
    rect_gp = gpar(col = "black", lwd = 2),
    width = unit(10 * ncol(merged.result),"mm"),
    height = unit(10 * nrow(merged.result),"mm"),
    column_names_gp = grid::gpar(fontsize = 15),
    row_names_gp = grid::gpar(fontsize = 15),
    );
heatmap.path <- paste0(output.path, system.date, '-', keyword, '-proportion-heatmap.png');
png(
    filename = heatmap.path,
    width = 14,
    height = 14,
    units = 'in',
    res = 400
    );
draw(plot, padding = unit(c(150, 50, 100, 50), "mm"));
dev.off();

### OUTPUT ########################################################################################
write.table(
    merged.result,
    file = paste0(output.path, system.date, '-', keyword, '-merged-proportion.txt'),
    sep = '\t',
    row.names = TRUE,
    col.names = TRUE,
    quote = FALSE
    );
